#install.packages(c('sp', 'rgdal'))

library(sp)
library(rgdal)

# Utility script to take the generated CleanNIPostcodeData.csv file generated by Section_1.R, and 
# generate a file that contains the primary key from that file, and the X / Y coordinates from the file
# (encoded in the Irish Grid system) converted to Longitude and Latitude.

# Credit for this solution goes to this StackOverFlow post:
# https://gis.stackexchange.com/questions/258864/converting-northings-eastings-to-longitude-latitude-using-r-issue-with-northern/258865
# And also to this Github repo: 
# https://gist.github.com/rCarto/5c36b2bd9a47e62612b20a306ab4fc48

# Download the RDS Dataset for the Irish Grid
download.file(url = "http://biogeo.ucdavis.edu/data/gadm2.8/rds/IRL_adm0.rds",
              file.path(tempdir(),"IRL_adm0.rds"))
# Parse that into an RDS file
IRL <- readRDS(file.path(tempdir(),"IRL_adm0.rds"))

# Load the postcode data
clean_ni_postcode_data <- read.csv("../NI_Crime_Data/CleanNIPostcodeData.csv")

# Construct a coordinate dataset with the X and Y Irish grid coordinates
coords <- cbind(X_coord = as.numeric(as.character(clean_ni_postcode_data$x_coordinates)),y_coord = as.numeric(as.character(clean_ni_postcode_data$y_coordinates)))
# Load the coordinates into a SpatialPointsDataFrame, sending in the contact that this is an Irish Grid representation in the proj4string param
postcode_SP <- SpatialPointsDataFrame(coords, data = data.frame(clean_ni_postcode_data$Primary_Key), proj4string = CRS("+init=epsg:29903"))
# Transform the data into another SpatialPointsDataFrame that holds the Longitude and Latitude for the data
postcode_LL <- spTransform(postcode_SP, CRS("+init=epsg:4326"))

# Format the transformed data into a dataframe
coords <- data.frame(postcode_LL$clean_ni_postcode_data.Primary_Key, postcode_LL@coords)
colnames(coords) <- c('postcode_PK', 'Long', 'Lat')

# And save it to a known location in the source code
write.csv(coords, 'PreComputed/PostCode_XY_to_LL.csv')

